In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [2]:
## this url contains the top most viewed movie pages on IMDB within a specified period of time
url = 'https://www.imdb.com/chart/moviemeter?sort=rk,asc&mode=simple&page=1'

In [3]:
page = requests.get(url)
page

In [4]:
## check the page source code
# page.content

In [5]:
soup = BeautifulSoup(page.content, "html.parser")

In [6]:
## get movie names
movie_name_info = soup.find_all('td', class_='titleColumn')
movie_name_info

[<td class="titleColumn">
 <a href="/title/tt9114286/" title="Ryan Coogler (dir.), Letitia Wright, Lupita Nyong'o">Black Panther: Wakanda Forever</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">1
 (no change)
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt10999120/" title="Sean Anders (dir.), Will Ferrell, Ryan Reynolds">Spirited</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">2
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 8)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt9764362/" title="Mark Mylod (dir.), Ralph Fiennes, Anya Taylor-Joy">The Menu</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">3
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 1)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt1596342/" title="Adam Shankman (dir.), Amy Adams, Patrick Dempsey">Disenchanted</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">4
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 1)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt17220704/" title="Clay Kaytis (dir.), Peter Billingsley, Erinn Hayes">A Christmas Story Christmas</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">5
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 6)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt13320662/" title="Francis Lawrence (dir.), Jason Momoa, Marlow Barkley">Slumberland</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">6
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 23)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt9288822/" title="Sebastián Lelio (dir.), Florence Pugh, Tom Burke">The Wonder</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">7
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 2)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt1630029/" title="James Cameron (dir.), Zoe Saldana, Kate Winslet">Avatar: The Way of Water</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">8
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 27)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt10168670/" title="Luca Guadagnino (dir.), Timothée Chalamet, Taylor Russell">Bones and All</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">9
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 17)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt6443346/" title="Jaume Collet-Serra (dir.), Dwayne Johnson, Aldis Hodge">Black Adam</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">10
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 7)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt0085334/" title="Bob Clark (dir.), Peter Billingsley, Melinda Dillon">A Christmas Story</a>
 <span class="secondaryInfo">(1983)</span>
 <div class="velocity">11
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 14)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt11564570/" title="Rian Johnson (dir.), Daniel Craig, Edward Norton">Glass Onion: A Knives Out Mystery</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">12
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 18)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt15474916/" title="Parker Finn (dir.), Sosie Bacon, Jessie T. Usher">Smile</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">13
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 6)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt10731256/" title="Olivia Wilde (dir.), Florence Pugh, Harry Styles">Don't Worry Darling</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">14
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 10)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt0461770/" title="Kevin Lima (dir.), Amy Adams, Susan Sarandon">Enchanted</a>
 <span class="secondaryInfo">(2007)</span>
 <div class="velocity">15
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 22)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt9411972/" title="Olivia Newman (dir.), Daisy Edgar-Jones, Taylor John Smith">Where the Crawdads Sing</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">16
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 10)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt14208870/" title="Steven Spielberg (dir.), Michelle Williams, Gabriel LaBelle">The Fabelmans</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">17
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 7)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt7322224/" title="Ruben Östlund (dir.), Harris Dickinson, Charlbi Dean">Triangle of Sadness</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">18
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 30)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt10298840/" title="Don Hall (dir.), Jake Gyllenhaal, Jaboukie Young-White">Strange World</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">19
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 45)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt0093748/" title="John Hughes (dir.), Steve Martin, John Candy">Planes, Trains &amp; Automobiles</a>
 <span class="secondaryInfo">(1987)</span>
 <div class="velocity">20
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 169)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt9071456/" title="Claire Scanlon (dir.), Allison Janney, Ben Platt">The People We Hate at the Wedding</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">21
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 35)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt10954984/" title="Jordan Peele (dir.), Daniel Kaluuya, Keke Palmer">Nope</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">22
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 18)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt15791034/" title="Zach Cregger (dir.), Georgina Campbell, Bill Skarsgård">Barbarian</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">23
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 8)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt12593682/" title="David Leitch (dir.), Brad Pitt, Joey King">Bullet Train</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">24
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 4)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt15501640/" title="Abhishek Pathak (dir.), Ajay Devgn, Tabu">Drishyam 2</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">25
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 85)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt13560574/" title="Ti West (dir.), Mia Goth, Jenna Ortega">X</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">26
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 10)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt14715170/" title="Janeen Damian (dir.), Lindsay Lohan, Chord Overstreet">Falling for Christmas</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">27
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 19)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt14807308/" title="Maria Schrader (dir.), Carey Mulligan, Zoe Kazan">She Said</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">28
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 13)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt17076046/" title="Eric Appel (dir.), Diedrich Bader, Daniel Radcliffe">Weird: The Al Yankovic Story</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">29
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 16)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt1016150/" title="Edward Berger (dir.), Felix Kammerer, Albrecht Schuch">Im Westen nichts Neues</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">30
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 16)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt13833688/" title="Darren Aronofsky (dir.), Brendan Fraser, Sadie Sink">The Whale</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">31
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 12)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt1745960/" title="Joseph Kosinski (dir.), Tom Cruise, Jennifer Connelly">Top Gun: Maverick</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">32
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 1)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt14641788/" title="Harry Bradbeer (dir.), Millie Bobby Brown, Henry Cavill">Enola Holmes 2</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">33
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 21)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt15789038/" title="Peter Sohn (dir.), Leah Lewis, Mamoudou Athie">Elemental</a>
 <span class="secondaryInfo">(2023)</span>
 <div class="velocity">34
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 10)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt15824322/" title="Gabriela Tagliavini (dir.), Aimee Garcia, Freddie Prinze Jr.">Christmas with You</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">35
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 46)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt13007592/" title="Charles Shyer (dir.), Justin Hartley, Bonnie Bedelia">The Noel Diary</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">36
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 1,366)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt11813216/" title="Martin McDonagh (dir.), Colin Farrell, Brendan Gleeson">The Banshees of Inisherin</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">37
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 15)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt7693316/" title="J.D. Dillard (dir.), Jonathan Majors, Glen Powell">Devotion</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">38
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 68)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt6710474/" title="Dan Kwan (dir.), Michelle Yeoh, Stephanie Hsu">Everything Everywhere All at Once</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">39
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 7)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt10304142/" title="David O. Russell (dir.), Christian Bale, Margot Robbie">Amsterdam</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">40
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 24)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt10403420/" title="Damien Leone (dir.), Lauren LaVera, David Howard Thornton">Terrifier 2</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">41
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 20)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt0097958/" title="Jeremiah S. Chechik (dir.), Chevy Chase, Beverly D'Angelo">National Lampoon's Christmas Vacation</a>
 <span class="secondaryInfo">(1989)</span>
 <div class="velocity">42
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 43)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt8946378/" title="Rian Johnson (dir.), Daniel Craig, Chris Evans">Knives Out</a>
 <span class="secondaryInfo">(2019)</span>
 <div class="velocity">43
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 28)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt1825683/" title="Ryan Coogler (dir.), Chadwick Boseman, Michael B. Jordan">Black Panther</a>
 <span class="secondaryInfo">(2018)</span>
 <div class="velocity">44
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 26)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt14444726/" title="Todd Field (dir.), Cate Blanchett, Noémie Merlant">Tár</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">45
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 17)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt13640696/" title="Tom George (dir.), Kieran Hodgson, Pearl Chanda">See How They Run</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">46
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 14)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt1488589/" title="Guillermo del Toro (dir.), Ewan McGregor, David Bradley">Pinocchio</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">47
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 19)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt10343028/" title="James Gray (dir.), Anne Hathaway, Jeremy Strong">Armageddon Time</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">48
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 24)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt15327088/" title="Rishab Shetty (dir.), Rishab Shetty, Kishore Kumar G.">Kantara</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">49
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 1)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt0499549/" title="James Cameron (dir.), Sam Worthington, Zoe Saldana">Avatar</a>
 <span class="secondaryInfo">(2009)</span>
 <div class="velocity">50
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 30)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt12003946/" title="Tommy Wirkola (dir.), David Harbour, Beverly D'Angelo">Violent Night</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">51
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 3)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt1462764/" title="James Mangold (dir.), Harrison Ford, Phoebe Waller-Bridge">Untitled Indiana Jones Project</a>
 <span class="secondaryInfo">(2023)</span>
 <div class="velocity">52
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 71)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt21094994/" title="Paul Leyden (dir.), Jeffrey Donovan, Rachel Adedeji">R.I.P.D. 2: Rise of the Damned</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">53
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 14)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt14781036/" title="Vasilis Katsoupis (dir.), Willem Dafoe, Gene Bervoets">Inside</a>
 <span class="secondaryInfo">(2023)</span>
 <div class="velocity">54
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 54)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt0101272/" title="Barry Sonnenfeld (dir.), Anjelica Huston, Raul Julia">The Addams Family</a>
 <span class="secondaryInfo">(1991)</span>
 <div class="velocity">55
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 252)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt0099785/" title="Chris Columbus (dir.), Macaulay Culkin, Joe Pesci">Home Alone</a>
 <span class="secondaryInfo">(1990)</span>
 <div class="velocity">56
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 13)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt14714980/" title="Russell Crowe (dir.), Russell Crowe, Liam Hemsworth">Poker Face</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">57
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 40)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt18925334/" title="Ti West (dir.), Mia Goth, David Corenswet">Pearl</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">58
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 16)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt8093700/" title="Gina Prince-Bythewood (dir.), Viola Davis, Thuso Mbedu">The Woman King</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">59
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 14)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt4273800/" title="Tobias Lindholm (dir.), Eddie Redmayne, Jessica Chastain">The Good Nurse</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">60
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 33)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt10648342/" title="Taika Waititi (dir.), Chris Hemsworth, Natalie Portman">Thor: Love and Thunder</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">61
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter down"></span>
 12)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt12446086/" title="Aaron Schoenke (dir.), Jason David Frank, Aaron Schoenke">Legend of the White Dragon</a>
 <div class="velocity">62
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 6,907)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt5533370/" title="Bobby Moresco (dir.), Frank Grillo, Mira Sorvino">Lamborghini: The Man Behind the Legend</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">63
 <span class="secondaryInfo">(
 <span class="global-sprite titlemeter up"></span>
 11)</span>
 </div>
 </td>,
 <td class="titleColumn">
 <a href="/title/tt21819228/" title="Jonah Hill (dir.), Jonah Hill, Phil Stutz">Stutz</a>
 <span class="secondaryInfo">(2022)</span>
 <div class="velocity">64
 <span class="secondaryInfo">(

In [7]:
## tidy movie names
movie_names = []
for movie in movie_name_info:
    movie = movie.find('a')
    movie = movie.get_text().replace('\n', "")
    movie = movie.strip(" ")
    movie = movie.split("(")[0]
    movie_names.append(movie)
movie_names

['Black Panther: Wakanda Forever',
 'Spirited',
 'The Menu',
 'Disenchanted',
 'A Christmas Story Christmas',
 'Slumberland',
 'The Wonder',
 'Avatar: The Way of Water',
 'Bones and All',
 'Black Adam',
 'A Christmas Story',
 'Glass Onion: A Knives Out Mystery',
 'Smile',
 "Don't Worry Darling",
 'Enchanted',
 'Where the Crawdads Sing',
 'The Fabelmans',
 'Triangle of Sadness',
 'Strange World',
 'Planes, Trains & Automobiles',
 'The People We Hate at the Wedding',
 'Nope',
 'Barbarian',
 'Bullet Train',
 'Drishyam 2',
 'X',
 'Falling for Christmas',
 'She Said',
 'Weird: The Al Yankovic Story',
 'Im Westen nichts Neues',
 'The Whale',
 'Top Gun: Maverick',
 'Enola Holmes 2',
 'Elemental',
 'Christmas with You',
 'The Noel Diary',
 'The Banshees of Inisherin',
 'Devotion',
 'Everything Everywhere All at Once',
 'Amsterdam',
 'Terrifier 2',
 "National Lampoon's Christmas Vacation",
 'Knives Out',
 'Black Panther',
 'Tár',
 'See How They Run',
 'Pinocchio',
 'Armageddon Time',
 'Kantara',
 'Avatar',
 'Violent Night',
 'Untitled Indiana Jones Project',
 'R.I.P.D. 2: Rise of the Damned',
 'Inside',
 'The Addams Family',
 'Home Alone',
 'Poker Face',
 'Pearl',
 'The Woman King',
 'The Good Nurse',
 'Thor: Love and Thunder',
 'Legend of the White Dragon',
 'Lamborghini: The Man Behind the Legend',
 'Stutz',
 'The Godfather',
 'The Batman',
 'Babylon',
 'Ticket to Paradise',
 'Enola Holmes',
 'The Northman',
 "Roald Dahl's Matilda the Musical",
 'Lyle, Lyle, Crocodile',
 'My Policeman',
 'Elf',
 'The Swimmers',
 'Love Actually',
 'The Santa Clause',
 'Till',
 'Willow',
 'Addams Family Values',
 'Top Gun',
 'Dhokha: Round D Corner',
 'Terrifier',
 'How the Grinch Stole Christmas',
 'The Shawshank Redemption',
 "Harry Potter and the Sorcerer's Stone",
 'The Last Manhunt',
 'Rogue One',
 'White Noise',
 'Aftersun',
 'The Bad Guys',
 'Fall',
 'Elvis',
 'Monica O My Darling',
 'The School for Good and Evil',
 'The Wolf of Wall Street',
 'Once Upon a Time in Hollywood',
 'The Wizard of Oz',
 'Pulp Fiction',
 'Dune: Part One']

In [8]:
## get movie ids
movie_ids = []
for movie in movie_name_info:
    movie = movie.find('a')
    movie = movie.get("href")
    movie = movie.split("/")[2]
    movie_ids.append(movie)
movie_ids

['tt9114286',
 'tt10999120',
 'tt9764362',
 'tt1596342',
 'tt17220704',
 'tt13320662',
 'tt9288822',
 'tt1630029',
 'tt10168670',
 'tt6443346',
 'tt0085334',
 'tt11564570',
 'tt15474916',
 'tt10731256',
 'tt0461770',
 'tt9411972',
 'tt14208870',
 'tt7322224',
 'tt10298840',
 'tt0093748',
 'tt9071456',
 'tt10954984',
 'tt15791034',
 'tt12593682',
 'tt15501640',
 'tt13560574',
 'tt14715170',
 'tt14807308',
 'tt17076046',
 'tt1016150',
 'tt13833688',
 'tt1745960',
 'tt14641788',
 'tt15789038',
 'tt15824322',
 'tt13007592',
 'tt11813216',
 'tt7693316',
 'tt6710474',
 'tt10304142',
 'tt10403420',
 'tt0097958',
 'tt8946378',
 'tt1825683',
 'tt14444726',
 'tt13640696',
 'tt1488589',
 'tt10343028',
 'tt15327088',
 'tt0499549',
 'tt12003946',
 'tt1462764',
 'tt21094994',
 'tt14781036',
 'tt0101272',
 'tt0099785',
 'tt14714980',
 'tt18925334',
 'tt8093700',
 'tt4273800',
 'tt10648342',
 'tt12446086',
 'tt5533370',
 'tt21819228',
 'tt0068646',
 'tt1877830',
 'tt10640346',
 'tt14109724',
 'tt7846844',
 'tt11138512',
 'tt3447590',
 'tt14668630',
 'tt13139228',
 'tt0319343',
 'tt8745676',
 'tt0314331',
 'tt0111070',
 'tt4960748',
 'tt0096446',
 'tt0106220',
 'tt0092099',
 'tt10644708',
 'tt4281724',
 'tt0170016',
 'tt0111161',
 'tt0241527',
 'tt11399896',
 'tt3748528',
 'tt6160448',
 'tt19770238',
 'tt8115900',
 'tt15325794',
 'tt3704428',
 'tt15128068',
 'tt2935622',
 'tt0993846',
 'tt7131622',
 'tt0032138',
 'tt0110912',
 'tt1160419']

In [9]:
## get year of movie, most get ride of brackets to convert to int
## if year isn't available, we assign None
movie_years = []
for movie in movie_name_info:
    movie = movie.find('span', class_='secondaryInfo')
    movie = movie.get_text()
    movie = movie.replace("(", '')
    movie = movie.replace(")", '')
    if len(movie) > 4:
        movie = None
    movie_years.append(movie)
movie_years

['2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '1983',
 '2022',
 '2022',
 '2022',
 '2007',
 '2022',
 '2022',
 '2022',
 '2022',
 '1987',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2023',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '1989',
 '2019',
 '2018',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2009',
 '2022',
 '2023',
 '2022',
 '2023',
 '1991',
 '1990',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 None,
 '2022',
 '2022',
 '1972',
 '2022',
 '2022',
 '2022',
 '2020',
 '2022',
 '2022',
 '2022',
 '2022',
 '2003',
 '2022',
 '2003',
 '1994',
 '2022',
 '1988',
 '1993',
 '1986',
 '2022',
 '2016',
 '2000',
 '1994',
 '2001',
 '2022',
 '2016',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2013',
 '2019',
 '1939',
 '1994',
 '2021']

In [10]:
## get movie rating info
movie_rating_info = soup.find_all('td', class_='ratingColumn imdbRating')
movie_rating_info

[<td class="ratingColumn imdbRating">
 <strong title="7.3 based on 100,053 user ratings">7.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.6 based on 14,210 user ratings">6.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.5 based on 21,908 user ratings">7.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="5.8 based on 11,854 user ratings">5.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.0 based on 5,622 user ratings">7.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.7 based on 10,465 user ratings">6.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.7 based on 14,843 user ratings">6.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.3 based on 5,989 user ratings">7.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.8 based on 142,779 user ratings">6.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 150,881 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 9,092 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.7 based on 66,522 user ratings">6.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.2 based on 71,758 user ratings">6.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.1 based on 203,609 user ratings">7.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.1 based on 58,958 user ratings">7.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 3,617 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 24,464 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="4.9 based on 5,300 user ratings">4.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.6 based on 144,091 user ratings">7.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="5.7 based on 3,534 user ratings">5.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.9 based on 164,084 user ratings">6.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.1 based on 88,416 user ratings">7.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.3 based on 187,011 user ratings">7.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.8 based on 15,924 user ratings">8.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.6 based on 88,635 user ratings">6.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="5.3 based on 12,968 user ratings">5.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.4 based on 3,556 user ratings">7.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.1 based on 18,159 user ratings">7.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 71,383 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 4,216 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 435,523 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.8 based on 52,846 user ratings">6.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="5.6 based on 3,174 user ratings">5.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.2 based on 3,844 user ratings">6.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 15,336 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.0 based on 1,447 user ratings">7.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 242,533 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.1 based on 25,766 user ratings">6.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.3 based on 20,536 user ratings">6.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.5 based on 189,273 user ratings">7.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 624,324 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.3 based on 766,012 user ratings">7.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 8,582 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.5 based on 30,264 user ratings">6.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 1,582 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.8 based on 4,294 user ratings">6.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.9 based on 73,239 user ratings">8.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 1,247,536 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 </td>,
 <td class="ratingColumn imdbRating">
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="4.5 based on 1,920 user ratings">4.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.9 based on 159,014 user ratings">6.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 567,627 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="5.1 based on 3,495 user ratings">5.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.0 based on 27,198 user ratings">7.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.7 based on 35,299 user ratings">6.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.8 based on 42,990 user ratings">6.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.3 based on 314,467 user ratings">6.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="5.2 based on 1,749 user ratings">5.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 4,248 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="9.2 based on 1,847,174 user ratings">9.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 626,475 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.2 based on 25,857 user ratings">6.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.6 based on 188,475 user ratings">6.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.1 based on 192,024 user ratings">7.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.5 based on 796 user ratings">7.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.2 based on 3,563 user ratings">6.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.5 based on 11,819 user ratings">6.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.0 based on 268,671 user ratings">7.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.4 based on 3,945 user ratings">7.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.6 based on 481,214 user ratings">7.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.5 based on 117,781 user ratings">6.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.3 based on 2,863 user ratings">7.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.2 based on 116,158 user ratings">7.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.8 based on 96,076 user ratings">6.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.9 based on 438,450 user ratings">6.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.1 based on 9,276 user ratings">7.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="5.6 based on 33,110 user ratings">5.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.2 based on 247,879 user ratings">6.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="9.3 based on 2,665,508 user ratings">9.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.6 based on 777,161 user ratings">7.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="4.1 based on 253 user ratings">4.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 635,550 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.6 based on 646 user ratings">6.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 4,835 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.8 based on 38,812 user ratings">6.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="6.4 based on 43,287 user ratings">6.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.4 based on 147,345 user ratings">7.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.5 based on 9,748 user ratings">7.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="5.8 based on 23,354 user ratings">5.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 1,399,221 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.6 based on 731,272 user ratings">7.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 400,201 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.9 based on 2,040,322 user ratings">8.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 626,953 user ratings">8.0</strong>
 </td>]

In [11]:
## get movie ratings
movie_ratings = []
for movie in movie_rating_info:
    movie = movie.get_text().replace("\n","")
    movie_ratings.append(movie)
movie_ratings

['7.3',
 '6.6',
 '7.5',
 '5.8',
 '7.0',
 '6.7',
 '6.7',
 '',
 '7.3',
 '6.8',
 '7.9',
 '8.1',
 '6.7',
 '6.2',
 '7.1',
 '7.1',
 '8.3',
 '7.7',
 '4.9',
 '7.6',
 '5.7',
 '6.9',
 '7.1',
 '7.3',
 '8.8',
 '6.6',
 '5.3',
 '7.4',
 '7.1',
 '7.8',
 '8.5',
 '8.4',
 '6.8',
 '',
 '5.6',
 '6.2',
 '8.2',
 '7.0',
 '8.1',
 '6.1',
 '6.3',
 '7.5',
 '7.9',
 '7.3',
 '7.9',
 '6.5',
 '8.1',
 '6.8',
 '8.9',
 '7.8',
 '',
 '',
 '4.5',
 '',
 '6.9',
 '7.7',
 '5.1',
 '7.0',
 '6.7',
 '6.8',
 '6.3',
 '',
 '5.2',
 '8.1',
 '9.2',
 '7.9',
 '',
 '6.2',
 '6.6',
 '7.1',
 '7.5',
 '6.2',
 '6.5',
 '7.0',
 '7.4',
 '7.6',
 '6.5',
 '7.3',
 '7.2',
 '6.8',
 '6.9',
 '7.1',
 '5.6',
 '6.2',
 '9.3',
 '7.6',
 '4.1',
 '7.8',
 '6.6',
 '7.7',
 '6.8',
 '6.4',
 '7.4',
 '7.5',
 '5.8',
 '8.2',
 '7.6',
 '8.1',
 '8.9',
 '8.0']

In [12]:
## create dataframe using pandas
d = {'ID' : movie_ids, 'Name' : movie_names, 'Rating' : movie_ratings, 'Year' : movie_years}
df = pd.DataFrame(data = d)

In [13]:
df.head(10)

           ID                            Name Rating  Year
0   tt9114286  Black Panther: Wakanda Forever    7.3  2022
1  tt10999120                        Spirited    6.6  2022
2   tt9764362                        The Menu    7.5  2022
3   tt1596342                    Disenchanted    5.8  2022
4  tt17220704     A Christmas Story Christmas    7.0  2022
5  tt13320662                     Slumberland    6.7  2022
6   tt9288822                      The Wonder    6.7  2022
7   tt1630029        Avatar: The Way of Water         2022
8  tt10168670                   Bones and All    7.3  2022
9   tt6443346                      Black Adam    6.8  2022

In [14]:
## change rating column to type float and Year to Int
df['Rating'] = df['Rating'].replace([''], None)
df['Rating'] = df['Rating'].astype('float')
df['Year'] = df['Year'].astype('Int64')

In [17]:
df = df.sort_values(by=['Rating'], ascending = False)

In [18]:
## top 10 highest rated movies in the top 100 'hottest' movies
df.head(10)

            ID                       Name  Rating  Year
84   tt0111161   The Shawshank Redemption     9.3  1994
64   tt0068646              The Godfather     9.2  1972
48  tt15327088                    Kantara     8.9  2022
98   tt0110912               Pulp Fiction     8.9  1994
24  tt15501640                 Drishyam 2     8.8  2022
30  tt13833688                  The Whale     8.5  2022
31   tt1745960          Top Gun: Maverick     8.4  2022
16  tt14208870              The Fabelmans     8.3  2022
95   tt0993846    The Wolf of Wall Street     8.2  2013
36  tt11813216  The Banshees of Inisherin     8.2  2022